package com.icbc.financialinfo.modules.report;
import com.icbc.financialinfo.common.ApiResponse;import com.icbc.financialinfo.modules.report.AdminReportService.*;import com.icbc.financialinfo.modules.review.DepartmentBusinessException;import com.icbc.financialinfo.modules.review.ReviewQueryModels.*;import com.icbc.financialinfo.modules.review.ReviewQueryRepository;import org.springframework.core.io.FileSystemResource;import org.springframework.core.io.Resource;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.nio.charset.StandardCharsets;import java.nio.file.Path;import java.util.*;
@RestController @RequestMapping("/api/reports") public class ReportController{
 private final ReviewQueryRepository repository;private final AdminReportService adminService;public ReportController(ReviewQueryRepository r,AdminReportService a){repository=r;adminService=a;}
 @GetMapping public ApiResponse<Map<String,Object>> list(){return ApiResponse.ok(Map.of("items",List.of(),"total",0));}
 @GetMapping("/review") public ApiResponse<PageData<ReportSummary>> reviewReports(@RequestParam(defaultValue="1")int pageNum,@RequestParam(defaultValue="10")int pageSize,@RequestParam(defaultValue="")String reportDate,@RequestParam(defaultValue="")String status){int pn=Math.max(pageNum,1),ps=Math.min(Math.max(pageSize,1),100);return new ApiResponse<>(200,"查询成功",new PageData<>(repository.countReviewReports(reportDate,status),pn,ps,repository.findReviewPage(pn,ps,reportDate,status)));}
 @GetMapping("/admin/review") public ApiResponse<PageData<AdminReviewReportSummary>> adminReviewReports(@RequestParam(defaultValue="1")int pageNum,@RequestParam(defaultValue="10")int pageSize){int pn=Math.max(pageNum,1),ps=Math.min(Math.max(pageSize,1),100);return new ApiResponse<>(200,"查询成功",new PageData<>(repository.countAllReports(),pn,ps,repository.findAdminReviewPage(pn,ps)));}
 @GetMapping("/admin/reviewers") public ApiResponse<List<ReviewerOption>> reviewers(@RequestParam String stage){return ApiResponse.ok(adminService.reviewers(stage));}
 @PutMapping("/admin/{id}/review-management") public ApiResponse<Void> manage(@PathVariable long id,@RequestBody ManageRequest request){adminService.manage(id,request==null?null:request.stage(),request==null?null:request.reviewerId());return new ApiResponse<>(200,"报告审核信息修改成功",null);}
 @GetMapping("/admin/{id}/archive/pdf") public ResponseEntity<Resource> archivedPdf(@PathVariable long id){Path path=adminService.archivedPdf(id);ContentDisposition disposition=ContentDisposition.inline().filename(path.getFileName().toString(),StandardCharsets.UTF_8).build();return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).contentLength(path.toFile().length()).header(HttpHeaders.CONTENT_DISPOSITION,disposition.toString()).body(new FileSystemResource(path));}
 @ExceptionHandler(DepartmentBusinessException.class) public ResponseEntity<ApiResponse<Object>> adminError(DepartmentBusinessException e){return ResponseEntity.status(e.status()).body(new ApiResponse<>(e.status(),e.getMessage(),null));}
 @GetMapping("/{id}/review-detail") public ResponseEntity<ApiResponse<ReportReviewDetail>> detail(@PathVariable long id){return repository.findReport(id).map(r->ResponseEntity.ok(new ApiResponse<>(200,"查询成功",new ReportReviewDetail(r.id(),r.reportDate(),r.reportTitle(),r.status(),r.locked(),r.lockedBy(),r.lockedAt(),r.createdAt(),r.updatedAt(),repository.findLatestDepartmentComment(id))))).orElseGet(()->ResponseEntity.status(404).body(new ApiResponse<>(404,"报告不存在",null)));}
}
