package com.icbc.financialinfo.modules.review;
import com.icbc.financialinfo.modules.review.ReviewIssueModels.ReviewIssue;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.util.*;
@Repository public class ReviewIssueRepository{
 private final JdbcTemplate jdbc;public ReviewIssueRepository(JdbcTemplate j){jdbc=j;}
 public boolean reportExists(long id){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM report WHERE id=?",Integer.class,id);return n!=null&&n>0;}
 public List<ReviewIssue> findIssues(long reportId){return jdbc.query("SELECT i.id,a.report_id,i.article_id,CASE i.issue_type WHEN 'SENSITIVE' THEN 'SENSITIVE_CONTENT' WHEN 'DATA_MISMATCH' THEN 'DATA_INCONSISTENCY' ELSE i.issue_type END issue_type,i.matched_text,i.start_offset,i.end_offset,i.message,i.resolved,i.resolved_by,DATE_FORMAT(i.resolved_at,'%Y-%m-%d %H:%i:%s') resolved_at,DATE_FORMAT(i.created_at,'%Y-%m-%d %H:%i:%s') created_at FROM review_issue i JOIN report_article a ON a.id=i.article_id WHERE a.report_id=? ORDER BY i.article_id,i.start_offset,i.id",(r,n)->new ReviewIssue(r.getLong("id"),r.getLong("report_id"),r.getLong("article_id"),r.getString("issue_type"),r.getString("matched_text"),r.getInt("start_offset"),r.getInt("end_offset"),r.getString("message"),r.getInt("resolved"),r.getObject("resolved_by",Long.class),r.getString("resolved_at"),r.getString("created_at")),reportId);}
 public List<CheckArticle> findCheckArticles(long reportId){return jdbc.query("SELECT a.id article_id,a.summary_content,n.content source_content FROM report_article a JOIN news_pool n ON n.id=a.news_id WHERE a.report_id=? ORDER BY a.id",(r,n)->new CheckArticle(r.getLong("article_id"),r.getString("summary_content"),r.getString("source_content")),reportId);}
 public void deleteIssues(long reportId){jdbc.update("DELETE i FROM review_issue i JOIN report_article a ON a.id=i.article_id WHERE a.report_id=?",reportId);}
 public void insertIssue(long articleId,String type,String text,int start,int end,String message){jdbc.update("INSERT INTO review_issue(article_id,issue_type,matched_text,start_offset,end_offset,message,resolved,created_at) VALUES(?,?,?,?,?,?,0,CURRENT_TIMESTAMP)",articleId,type,text,start,end,message);}
 public Optional<IssueState> lockIssue(long id){return jdbc.query("SELECT id,resolved FROM review_issue WHERE id=? FOR UPDATE",(r,n)->new IssueState(r.getLong("id"),r.getInt("resolved")),id).stream().findFirst();}
 public void resolveIssue(long id,long user){jdbc.update("UPDATE review_issue SET resolved=1,resolved_by=?,resolved_at=CURRENT_TIMESTAMP WHERE id=?",user,id);}
 public record CheckArticle(Long articleId,String summaryContent,String sourceContent){} public record IssueState(Long id,Integer resolved){}
}
