package com.icbc.financialinfo.modules.review;
import com.icbc.financialinfo.modules.review.ReviewCommandModels.ReplacementArticle;import com.icbc.financialinfo.modules.review.ReviewQueryModels.ReviewRecordView;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.support.*;import org.springframework.stereotype.Repository;import java.sql.*;import java.util.*;
@Repository public class ReviewCommandRepository{
 private final JdbcTemplate jdbc;public ReviewCommandRepository(JdbcTemplate j){jdbc=j;}
 public void normalizeLegacyStatus(long reportId){jdbc.update("UPDATE report SET status=CASE status WHEN 'INITIAL_REVIEW' THEN 'INITIAL_PENDING' WHEN 'FINAL_REVIEW' THEN 'FINAL_PENDING' ELSE status END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN('INITIAL_REVIEW','FINAL_REVIEW')",reportId);}
 public Optional<ReportState> report(long id,boolean lock){return jdbc.query("SELECT id,DATE_FORMAT(report_date,'%Y-%m-%d') report_date,status,locked,locked_by FROM report WHERE id=?"+(lock?" FOR UPDATE":""),(r,n)->new ReportState(r.getLong("id"),r.getString("report_date"),r.getString("status"),r.getInt("locked"),r.getObject("locked_by",Long.class)),id).stream().findFirst();}
 public Optional<ArticleState> article(long id){return jdbc.query("SELECT id,report_id,news_id,category,title,summary_content FROM report_article WHERE id=? AND select_type='selected'",(r,n)->new ArticleState(r.getLong("id"),r.getLong("report_id"),r.getLong("news_id"),r.getString("category"),r.getString("title"),r.getString("summary_content")),id).stream().findFirst();}
 public Optional<AlternativeState> alternative(long reportId,long newsId){return jdbc.query("SELECT id,report_id,news_id,category,title,summary_content,reason FROM report_article WHERE report_id=? AND news_id=? AND select_type='alternatives'",(r,n)->new AlternativeState(r.getLong("id"),r.getLong("report_id"),r.getLong("news_id"),r.getString("category"),r.getString("title"),r.getString("summary_content"),r.getString("reason")),reportId,newsId).stream().findFirst();}
 public Optional<NewsState> news(long id){return jdbc.query("SELECT id,DATE_FORMAT(news_date,'%Y-%m-%d') news_date,title,content,industry,area FROM news_pool WHERE id=?",(r,n)->new NewsState(r.getLong("id"),r.getString("news_date"),r.getString("title"),r.getString("content"),r.getString("industry"),r.getString("area")),id).stream().findFirst();}
 public void updateArticle(long id,String title,String summary){jdbc.update("UPDATE report_article SET title=?,summary_content=? WHERE id=? AND select_type='selected'",title,summary,id);}
 public void replaceArticle(long selectedArticleId,long alternativeArticleId,String reason){jdbc.update("UPDATE report_article SET select_type='alternatives',reason=? WHERE id=? AND select_type='selected'",reason,selectedArticleId);jdbc.update("UPDATE report_article SET select_type='selected' WHERE id=? AND select_type='alternatives'",alternativeArticleId);}
 public void status(long reportId,String status,long operator){jdbc.update("UPDATE report SET status=?,locked=1,locked_by=?,locked_at=COALESCE(locked_at,CURRENT_TIMESTAMP),updated_at=CURRENT_TIMESTAMP WHERE id=?",status,operator,reportId);}
 public void finish(long reportId,String status,long operator){if("FINAL_APPROVED".equals(status))jdbc.update("UPDATE report SET status=?,locked=1,locked_by=?,locked_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",status,operator,reportId);else jdbc.update("UPDATE report SET status=?,locked=0,locked_by=NULL,locked_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?",status,reportId);}
 public long record(long reportId,Long articleId,long operator,String action,String before,String after,String reason,String comment){Long taskId=jdbc.query("SELECT id FROM review_task WHERE report_id=? AND reviewer_id=? ORDER BY id DESC LIMIT 1",(r,n)->r.getLong(1),reportId,operator).stream().findFirst().orElse(null);KeyHolder k=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement s=c.prepareStatement("INSERT INTO review_record(review_task_id,report_id,article_id,operator_id,action_type,before_content,after_content,reason,comment_text,created_at) VALUES(?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)",Statement.RETURN_GENERATED_KEYS);if(taskId==null)s.setNull(1,Types.BIGINT);else s.setLong(1,taskId);s.setLong(2,reportId);if(articleId==null)s.setNull(3,Types.BIGINT);else s.setLong(3,articleId);s.setLong(4,operator);s.setString(5,action);s.setString(6,before);s.setString(7,after);s.setString(8,reason);s.setString(9,comment);return s;},k);return k.getKey().longValue();}
 public void assignToUsername(long reportId,String username,String comment){Long userId=jdbc.query("SELECT id FROM sys_user WHERE username=? AND status=1",(r,n)->r.getLong(1),username).stream().findFirst().orElseThrow(()->new IllegalStateException("未找到审核人员："+username));upsertAssignment(reportId,userId,comment,false);}
 public void assignToRole(long reportId,String roleCode,String comment){Long userId=jdbc.query("SELECT u.id FROM sys_user u JOIN sys_role r ON r.id=u.role_id WHERE r.role_code=? AND u.status=1 ORDER BY u.id LIMIT 1",(r,n)->r.getLong(1),roleCode).stream().findFirst().orElseThrow(()->new IllegalStateException("未找到角色审核人员："+roleCode));upsertAssignment(reportId,userId,comment,false);}
 public void completeAssignment(long reportId,long reviewerId,String comment){jdbc.update("UPDATE review_task SET review_comment=?,completed_at=CURRENT_TIMESTAMP WHERE report_id=? AND reviewer_id=?",comment,reportId,reviewerId);}
 private void upsertAssignment(long reportId,long reviewerId,String comment,boolean completed){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM review_task WHERE report_id=? AND reviewer_id=?",Integer.class,reportId,reviewerId);if(n==null||n==0)jdbc.update("INSERT INTO review_task(report_id,reviewer_id,review_comment,submitted_at,completed_at) VALUES(?,?,?,CURRENT_TIMESTAMP,NULL)",reportId,reviewerId,comment);else jdbc.update("UPDATE review_task SET review_comment=?,submitted_at=CURRENT_TIMESTAMP,completed_at=NULL WHERE report_id=? AND reviewer_id=?",comment,reportId,reviewerId);}
 public List<ReplacementArticle> replacements(long reportId,String category,String keyword){List<Object> p=new ArrayList<>(List.of(reportId));String q="SELECT a.id article_id,a.news_id,DATE_FORMAT(n.news_date,'%Y-%m-%d') news_date,a.category,a.title,n.industry,n.area,a.summary_content,a.reason FROM report_article a LEFT JOIN news_pool n ON n.id=a.news_id WHERE a.report_id=? AND a.select_type='alternatives'";if(category!=null&&!category.isBlank()){q+=" AND a.category=?";p.add(category.trim());}if(keyword!=null&&!keyword.isBlank()){q+=" AND a.title LIKE ?";p.add("%"+keyword.trim()+"%");}q+=" ORDER BY a.id LIMIT 100";return jdbc.query(q,(r,i)->new ReplacementArticle(r.getLong("article_id"),r.getLong("news_id"),r.getString("news_date"),r.getString("category"),r.getString("title"),r.getString("industry"),r.getString("area"),r.getString("summary_content"),r.getString("reason")),p.toArray());}
 public List<ReviewRecordView> records(long reportId){return jdbc.query("SELECT rr.id,rr.article_id,rr.operator_id,u.username operator_username,rr.action_type,rr.before_content,rr.reason,rr.comment_text,DATE_FORMAT(rr.created_at,'%Y-%m-%d %H:%i:%s') created_at FROM review_record rr JOIN sys_user u ON u.id=rr.operator_id WHERE rr.report_id=? AND rr.action_type IN('ANNOTATE','COMMENT','MARK_MODIFY') ORDER BY rr.id",(r,n)->new ReviewRecordView(r.getLong("id"),r.getObject("article_id",Long.class),sequence(reportId,r.getObject("article_id",Long.class)),r.getLong("operator_id"),r.getString("operator_username"),r.getString("action_type"),r.getString("before_content"),r.getString("reason"),r.getString("comment_text"),r.getString("created_at")),reportId);}
 private Integer sequence(long reportId,Long articleId){if(articleId==null)return null;List<Long> ids=jdbc.query("SELECT id FROM report_article WHERE report_id=? AND select_type='selected' ORDER BY id",(r,n)->r.getLong(1),reportId);int i=ids.indexOf(articleId);return i<0?null:i+1;}
 public record ReportState(Long id,String reportDate,String status,Integer locked,Long lockedBy){}
 public record ArticleState(Long id,Long reportId,Long newsId,String category,String title,String summaryContent){}
 public record NewsState(Long id,String newsDate,String title,String content,String industry,String area){}
 public record AlternativeState(Long id,Long reportId,Long newsId,String category,String title,String summaryContent,String reason){}
}
