package com.icbc.financialinfo.modules.review;
import com.icbc.financialinfo.modules.review.ReviewQueryModels.*;
import org.springframework.jdbc.core.*;import org.springframework.stereotype.Repository;import java.util.*;
@Repository public class ReviewQueryRepository {
 private final JdbcTemplate jdbc;
 private static final String RC="SELECT r.id,DATE_FORMAT(r.report_date,'%Y-%m-%d') report_date,r.report_title,r.status,r.locked,r.locked_by,DATE_FORMAT(r.locked_at,'%Y-%m-%d %H:%i:%s') locked_at,DATE_FORMAT(r.created_at,'%Y-%m-%d %H:%i:%s') created_at,DATE_FORMAT(r.updated_at,'%Y-%m-%d %H:%i:%s') updated_at FROM report r";
 private static final RowMapper<ReportSummary> RM=(r,n)->new ReportSummary(r.getLong("id"),r.getString("report_date"),r.getString("report_title"),r.getString("status"),r.getInt("locked"),r.getObject("locked_by",Long.class),r.getString("locked_at"),r.getString("created_at"),r.getString("updated_at"));
 public ReviewQueryRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private String fullStatus(String stage,String status){String p=stage.toUpperCase()+"_",v=status.trim().toUpperCase();return v.startsWith(p)?v:p+v;}
 public void ensureMissingTasks(){jdbc.update("UPDATE report SET status=CASE status WHEN 'INITIAL_REVIEW' THEN 'INITIAL_PENDING' WHEN 'FINAL_REVIEW' THEN 'FINAL_PENDING' ELSE status END WHERE status IN('INITIAL_REVIEW','FINAL_REVIEW')");int changed=jdbc.update("INSERT INTO review_task(report_id,reviewer_id,review_comment,submitted_at,completed_at) SELECT r.id,u.id,NULL,CURRENT_TIMESTAMP,NULL FROM report r JOIN sys_user u ON u.username='info01' AND u.status=1 WHERE NOT EXISTS(SELECT 1 FROM review_task t WHERE t.report_id=r.id)");jdbc.update("INSERT INTO review_task(report_id,reviewer_id,review_comment,submitted_at,completed_at) SELECT r.id,u.id,'终审已退回',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM report r CROSS JOIN (SELECT su.id FROM sys_user su JOIN sys_role role ON role.id=su.role_id WHERE role.role_code='DEPT_MANAGER' AND su.status=1 ORDER BY su.id LIMIT 1) u WHERE r.status='INITIAL_REJECTED' AND NOT EXISTS(SELECT 1 FROM review_task t WHERE t.report_id=r.id AND t.reviewer_id=u.id)");if(changed<0)throw new IllegalStateException("审核任务初始化失败");}
 public List<AssignedTaskSummary> findAssignedTasks(long reviewerId,String stage,String status,int pageNum,int pageSize){String s=stage.toUpperCase();List<Object> p=new ArrayList<>(List.of(reviewerId));String where="t.reviewer_id=? AND "+("FINAL".equals(s)?"(r.status LIKE 'FINAL_%' OR r.status='INITIAL_REJECTED')":"r.status LIKE 'INITIAL_%'");if(status!=null&&!status.isBlank()){where+=" AND r.status=?";String shortStatus=status.trim().toUpperCase();p.add("FINAL".equals(s)&&"REJECTED".equals(shortStatus)?"INITIAL_REJECTED":fullStatus(s,shortStatus));}p.add(pageSize);p.add((pageNum-1)*pageSize);return jdbc.query("SELECT t.id,r.id report_id,'"+s+"' review_stage,r.status,DATE_FORMAT(r.report_date,'%Y-%m-%d') report_date,r.report_title,DATE_FORMAT(t.submitted_at,'%Y-%m-%d %H:%i:%s') submitted_at,DATE_FORMAT(t.completed_at,'%Y-%m-%d %H:%i:%s') completed_at FROM review_task t JOIN report r ON r.id=t.report_id WHERE "+where+" ORDER BY t.submitted_at DESC,t.id DESC LIMIT ? OFFSET ?",(r,n)->new AssignedTaskSummary(r.getLong("id"),r.getLong("report_id"),r.getString("review_stage"),r.getString("status"),r.getString("report_date"),r.getString("report_title"),r.getString("submitted_at"),r.getString("completed_at")),p.toArray());}
 public long countAssignedTasks(long reviewerId,String stage,String status){String s=stage.toUpperCase();List<Object> p=new ArrayList<>(List.of(reviewerId));String q="SELECT COUNT(*) FROM review_task t JOIN report r ON r.id=t.report_id WHERE t.reviewer_id=? AND "+("FINAL".equals(s)?"(r.status LIKE 'FINAL_%' OR r.status='INITIAL_REJECTED')":"r.status LIKE 'INITIAL_%'");if(status!=null&&!status.isBlank()){q+=" AND r.status=?";String shortStatus=status.trim().toUpperCase();p.add("FINAL".equals(s)&&"REJECTED".equals(shortStatus)?"INITIAL_REJECTED":fullStatus(s,shortStatus));}Long n=jdbc.queryForObject(q,Long.class,p.toArray());return n==null?0:n;}
 public Optional<ReportSummary> findReport(long id){return jdbc.query(RC+" WHERE r.id=?",RM,id).stream().findFirst();}
 public Optional<Long> findAssignedReportId(long taskOrReportId,long reviewerId){List<Long> exact=jdbc.query("SELECT report_id FROM review_task WHERE id=? AND reviewer_id=?",(r,n)->r.getLong(1),taskOrReportId,reviewerId);if(!exact.isEmpty())return Optional.of(exact.get(0));return jdbc.query("SELECT report_id FROM review_task WHERE report_id=? AND reviewer_id=? ORDER BY id DESC LIMIT 1",(r,n)->r.getLong(1),taskOrReportId,reviewerId).stream().findFirst();}
 public Optional<Map<String,Object>> findTaskDetail(long taskId,long reviewerId){return jdbc.query("SELECT t.id,t.report_id,t.reviewer_id,t.review_comment,DATE_FORMAT(t.submitted_at,'%Y-%m-%d %H:%i:%s') submitted_at,DATE_FORMAT(t.completed_at,'%Y-%m-%d %H:%i:%s') completed_at,r.report_title,DATE_FORMAT(r.report_date,'%Y-%m-%d') report_date,r.status,r.locked FROM review_task t JOIN report r ON r.id=t.report_id WHERE t.id=? AND t.reviewer_id=?",(r,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getLong("id"));m.put("reportId",r.getLong("report_id"));m.put("reviewerId",r.getLong("reviewer_id"));m.put("reviewStage",r.getString("status").startsWith("FINAL_")?"FINAL":"INITIAL");m.put("status",r.getString("status"));m.put("reviewComment",r.getString("review_comment"));m.put("submittedAt",r.getString("submitted_at"));m.put("completedAt",r.getString("completed_at"));m.put("report",Map.of("reportTitle",r.getString("report_title"),"reportDate",r.getString("report_date"),"locked",r.getInt("locked")));return m;},taskId,reviewerId).stream().findFirst();}
 public String findLatestDepartmentComment(long reportId){return jdbc.query("SELECT t.review_comment FROM review_task t JOIN sys_user u ON u.id=t.reviewer_id JOIN sys_role role ON role.id=u.role_id WHERE t.report_id=? AND role.role_code='DEPT_MANAGER' AND t.review_comment IS NOT NULL AND TRIM(t.review_comment)<>'' ORDER BY COALESCE(t.completed_at,t.submitted_at) DESC,t.id DESC LIMIT 1",(r,n)->r.getString(1),reportId).stream().findFirst().orElse(null);}
 public List<ReportSummary> findReviewPage(int pn,int ps,String date,String status){List<Object> p=new ArrayList<>();String w=" WHERE (r.status LIKE 'INITIAL_%' OR r.status LIKE 'FINAL_%')";if(date!=null&&!date.isBlank()){w+=" AND r.report_date=?";p.add(date.trim());}if(status!=null&&!status.isBlank()){w+=" AND r.status=?";p.add(status.trim().toUpperCase());}p.add(ps);p.add((pn-1)*ps);return jdbc.query(RC+w+" ORDER BY r.report_date DESC,r.id DESC LIMIT ? OFFSET ?",RM,p.toArray());}
 public long countReviewReports(String date,String status){List<Object> p=new ArrayList<>();String q="SELECT COUNT(*) FROM report WHERE (status LIKE 'INITIAL_%' OR status LIKE 'FINAL_%')";if(date!=null&&!date.isBlank()){q+=" AND report_date=?";p.add(date.trim());}if(status!=null&&!status.isBlank()){q+=" AND status=?";p.add(status.trim().toUpperCase());}Long n=jdbc.queryForObject(q,Long.class,p.toArray());return n==null?0:n;}
 public boolean reportExists(long id){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM report WHERE id=?",Integer.class,id);return n!=null&&n>0;}
 public List<ReportArticle> findArticles(long reportId){return jdbc.query("SELECT id,report_id,news_id,category,title,summary_content,DATE_FORMAT(created_at,'%Y-%m-%d %H:%i:%s') created_at FROM report_article WHERE report_id=? ORDER BY id",(r,n)->new ReportArticle(r.getLong("id"),r.getLong("report_id"),r.getLong("news_id"),n+1,r.getString("category"),r.getString("title"),r.getString("summary_content"),r.getString("created_at")),reportId);}
 public Optional<ArticleSource> findArticleSource(long id){return jdbc.query("SELECT a.id article_id,n.id news_id,n.daily_seq,n.source_row_id,DATE_FORMAT(n.news_date,'%Y-%m-%d') news_date,n.title,n.original_content,n.content,n.industry,n.area,n.content_hash FROM report_article a JOIN news_pool n ON n.id=a.news_id WHERE a.id=?",(r,n)->new ArticleSource(r.getLong("article_id"),r.getLong("news_id"),r.getInt("daily_seq"),r.getString("source_row_id"),r.getString("news_date"),r.getString("title"),r.getString("original_content"),r.getString("content"),r.getString("industry"),r.getString("area"),r.getString("content_hash")),id).stream().findFirst();}
 public List<ArticleSource> findReportSources(long reportId){return jdbc.query("SELECT NULL article_id,n.id news_id,n.daily_seq,n.source_row_id,DATE_FORMAT(n.news_date,'%Y-%m-%d') news_date,n.title,n.original_content,n.content,n.industry,n.area,n.content_hash FROM report r JOIN news_pool n ON n.news_date=r.report_date WHERE r.id=? ORDER BY n.daily_seq,n.id",(r,n)->new ArticleSource(null,r.getLong("news_id"),r.getInt("daily_seq"),r.getString("source_row_id"),r.getString("news_date"),r.getString("title"),r.getString("original_content"),r.getString("content"),r.getString("industry"),r.getString("area"),r.getString("content_hash")),reportId);}
}
